// <auto-generated />
using System;
using LCode.InfraestruCode.Core.BD.Contexto.v1_0;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LCode.InfraestruCode.Core.BD.Migrations
{
    [DbContext(typeof(LCODEContexto))]
    [Migration("20210602183102_CambioExtension")]
    partial class CambioExtension
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("lcode")
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("LCode.InfraestruCode.Core.BD.Contexto.v1_0.Modelos.ServidoresSolicitud", b =>
                {
                    b.Property<string>("GuidSolicitud")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("EstadoSolicitud")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHoraRegistro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraUltimaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mensaje")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Servidor")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<int>("TipoSolicitud")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioSolicita")
                        .HasColumnType("varchar(50)");

                    b.HasKey("GuidSolicitud");

                    b.ToTable("SolicitudesServidores");
                });
#pragma warning restore 612, 618
        }
    }
}
